// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimeManager.Backend.Data;

#nullable disable

namespace TimeManager.Backend.Migrations
{
    [DbContext(typeof(HrmsDbContext))]
    partial class HrmsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TimeManager.Backend.Models.Employee_Management.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("TimeManager.Backend.Models.Employee_Management.EmployeeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("EmployeeType");
                });

            modelBuilder.Entity("TimeManager.Backend.Models.Employee_Management.JobProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("ProfileTemplateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.HasIndex("ProfileTemplateId")
                        .IsUnique();

                    b.ToTable("JobProfile");
                });

            modelBuilder.Entity("TimeManager.Backend.Models.Employee_Management.PayFrequency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("PayFrequency");
                });

            modelBuilder.Entity("TimeManager.Backend.Models.Employee_Management.ProfileTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EarlyClockInBufferMin")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeTypeId")
                        .HasColumnType("int");

                    b.Property<int>("PayFrequencyId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("ShiftStartTime")
                        .HasColumnType("time(6)");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeTypeId")
                        .IsUnique();

                    b.HasIndex("PayFrequencyId")
                        .IsUnique();

                    b.HasIndex("RoleId")
                        .IsUnique();

                    b.HasIndex("UnitId")
                        .IsUnique();

                    b.ToTable("ProfileTemplate");
                });

            modelBuilder.Entity("TimeManager.Backend.Models.Employee_Management.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("TimeManager.Backend.Models.Organization_Management.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("TimeManager.Backend.Models.Organization_Management.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId")
                        .IsUnique();

                    b.ToTable("Unit");
                });

            modelBuilder.Entity("TimeManager.Backend.Models.Punch_Management.PayPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("PayPeriod");
                });

            modelBuilder.Entity("TimeManager.Backend.Models.Punch_Management.PunchEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ClockIn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ClockOut")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("JobProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JobProfileId");

                    b.ToTable("PunchEntry");
                });

            modelBuilder.Entity("TimeManager.Backend.Models.Employee_Management.JobProfile", b =>
                {
                    b.HasOne("TimeManager.Backend.Models.Employee_Management.Employee", "Employee")
                        .WithOne("JobProfile")
                        .HasForeignKey("TimeManager.Backend.Models.Employee_Management.JobProfile", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TimeManager.Backend.Models.Employee_Management.ProfileTemplate", "ProfileTemplate")
                        .WithOne("JobProfile")
                        .HasForeignKey("TimeManager.Backend.Models.Employee_Management.JobProfile", "ProfileTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("ProfileTemplate");
                });

            modelBuilder.Entity("TimeManager.Backend.Models.Employee_Management.ProfileTemplate", b =>
                {
                    b.HasOne("TimeManager.Backend.Models.Employee_Management.EmployeeType", "EmployeeType")
                        .WithOne("ProfileTemplate")
                        .HasForeignKey("TimeManager.Backend.Models.Employee_Management.ProfileTemplate", "EmployeeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TimeManager.Backend.Models.Employee_Management.PayFrequency", "PayFrequency")
                        .WithOne("ProfileTemplate")
                        .HasForeignKey("TimeManager.Backend.Models.Employee_Management.ProfileTemplate", "PayFrequencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TimeManager.Backend.Models.Employee_Management.Role", "Role")
                        .WithOne("ProfileTemplate")
                        .HasForeignKey("TimeManager.Backend.Models.Employee_Management.ProfileTemplate", "RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TimeManager.Backend.Models.Organization_Management.Unit", "Unit")
                        .WithOne("ProfileTemplate")
                        .HasForeignKey("TimeManager.Backend.Models.Employee_Management.ProfileTemplate", "UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeType");

                    b.Navigation("PayFrequency");

                    b.Navigation("Role");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("TimeManager.Backend.Models.Organization_Management.Unit", b =>
                {
                    b.HasOne("TimeManager.Backend.Models.Organization_Management.Department", "Department")
                        .WithOne("Unit")
                        .HasForeignKey("TimeManager.Backend.Models.Organization_Management.Unit", "DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("TimeManager.Backend.Models.Punch_Management.PunchEntry", b =>
                {
                    b.HasOne("TimeManager.Backend.Models.Employee_Management.JobProfile", "JobProfile")
                        .WithMany()
                        .HasForeignKey("JobProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobProfile");
                });

            modelBuilder.Entity("TimeManager.Backend.Models.Employee_Management.Employee", b =>
                {
                    b.Navigation("JobProfile");
                });

            modelBuilder.Entity("TimeManager.Backend.Models.Employee_Management.EmployeeType", b =>
                {
                    b.Navigation("ProfileTemplate");
                });

            modelBuilder.Entity("TimeManager.Backend.Models.Employee_Management.PayFrequency", b =>
                {
                    b.Navigation("ProfileTemplate");
                });

            modelBuilder.Entity("TimeManager.Backend.Models.Employee_Management.ProfileTemplate", b =>
                {
                    b.Navigation("JobProfile");
                });

            modelBuilder.Entity("TimeManager.Backend.Models.Employee_Management.Role", b =>
                {
                    b.Navigation("ProfileTemplate");
                });

            modelBuilder.Entity("TimeManager.Backend.Models.Organization_Management.Department", b =>
                {
                    b.Navigation("Unit");
                });

            modelBuilder.Entity("TimeManager.Backend.Models.Organization_Management.Unit", b =>
                {
                    b.Navigation("ProfileTemplate");
                });
#pragma warning restore 612, 618
        }
    }
}
